name: Sync Fork

on:
  schedule:
    - cron: '15 3 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - ignore_fail: true
        uses: tgymnich/fork-sync@master
        with:
          owner: joxda
          base: main
          head: main
